# This action is basically copied from https://github.com/oxinabox/CV
name: regenerate
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: memorial_amp.tex
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate PDF
          file_pattern: '*.pdf'
          branch: main